# Generated by Django 2.2 on 2019-05-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastusercontext',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MensagemNaoRespondida',
        ),
    ]
