# Generated by Django 2.2 on 2019-07-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usertelegram_grr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='grr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
