# Generated by Django 2.2 on 2019-07-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190723_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListAlgoritimos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grr', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListFundamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grr', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
