# Generated by Django 2.2.4 on 2019-08-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_listalgoritimos_listfundamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquitetura', models.BooleanField(default=False)),
                ('fundamentos', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.UserTelegram')),
            ],
            options={
                'db_table': 'permissões',
            },
        ),
        migrations.DeleteModel(
            name='ListAlgoritimos',
        ),
        migrations.DeleteModel(
            name='ListFundamentos',
        ),
    ]
