# Generated by Django 2.2.4 on 2019-08-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190824_1841'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permissoes',
            table='permissoes',
        ),
    ]
