# Generated by Django 2.2.4 on 2019-08-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190824_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='respondida',
            new_name='nao_respondida',
        ),
        migrations.AddField(
            model_name='message',
            name='respota',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
    ]
