# Generated by Django 2.2.4 on 2019-08-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190824_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='nao_respondida',
            new_name='nao_entendida',
        ),
    ]
